name: build-and-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout code
         uses: actions/checkout@v2

       - name: Set up C++ environment
         run: |
           sudo apt update
           sudo apt install -y build-essential libgsl-dev

       - name: Build everything with Make
         run: |
           cp make.config-template make.config
           make

       - name: Run tests
         run: ./tests/test_main

       - name: Run the examples
         run: |
           ./examples/corona
           ./examples/particles
           ./examples/singlezone
