name: build-and-test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout code
         uses: actions/checkout@v4

       - name: Install Doxygen
         run: |
           sudo apt update
           sudo apt install -y doxygen graphviz

       - name: Build Doxygen Documentation
         working-directory: ./docs
         run: doxygen Doxyfile

       - name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v4
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./docs/html  # Change this to the output directory of Doxygen
